plugins {
	id "com.crystaelix.loom" version "1.13-SNAPSHOT"
	id "eclipse"
	id "idea"
	id "maven-publish"
	id "com.crystaelix.blossom" version "1.3.2"
	id "me.modmuss50.mod-publish-plugin" version "1.1.0"
}

repositories {
	mavenCentral()
	flatDir {
		dirs "libs"
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.quiltmc.org/repository/release/"
			}
		}
		filter {
			includeGroup "org.quiltmc"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.parchmentmc.net/"
			}
		}
		filter {
			includeGroup "org.parchmentmc.data"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.nucleoid.xyz/"
			}
		}
		filter {
			includeGroup "eu.pb4"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.terraformersmc.com/"
			}
		}
		filter {
			includeGroup "com.terraformersmc"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.blamejared.com/"
			}
		}
		filter {
			includeGroup "mezz.jei"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.crystaelix.com/releases/"
			}
		}
		filter {
			includeGroup "thelm.jeidrawables"
			includeGroup "thelm.fractaljei"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.ladysnake.org/releases/"
			}
		}
		filter {
			includeGroup "dev.onyxstudios.cardinal-components-api"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://repo.unascribed.com/"
			}
		}
		filter {
			includeGroup "com.unascribed"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://cursemaven.com/"
			}
		}
		filter {
			includeGroup "curse.maven"
		}
	}
}

def mcVersion = "1.19.2"
def modName = "YttrJEI"
def modId = "yttrjei"
def specVersion = "19.2"
def vendor = "thelm"

group = "thelm.yttrjei"
version = "19.2.2"

def archivesName = modName
base.archivesName = archivesName

sourceSets {
	main
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
		vendor = JvmVendorSpec.AZUL
	}
	withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = "UTF-8"
}

loom {
	silentMojangMappingsLicense()
	runs {
		configureEach {
			property "fabric.log.console.level", "debug"
		}
		client {
			programArg "--username=Dev"
		}
		server
	}
}

dependencies {
	// Minecraft
	minecraft "com.mojang:minecraft:1.19.2"
	mappings loom.layered {
		mappings "net.fabricmc:yarn:1.19.2+build.28:v2"
		parchment "org.parchmentmc.data:parchment-1.19.2:2022.11.27@zip"
	}
	modImplementation "net.fabricmc:fabric-loader:0.18.1"
	modImplementation "net.fabricmc.fabric-api:fabric-api:0.77.0+1.19.2"
	modImplementation "eu.pb4:placeholder-api:2.0.0-pre.1+1.19.2"
	modImplementation "com.terraformersmc:modmenu:4.2.0-beta.2"

	// JEI
	modImplementation("mezz.jei:jei-1.19.2-fabric:11.8.1.1034") {transitive = false}
	include(modImplementation("thelm.jeidrawables:JEIDrawables-Fabric:19.2.7"))

	// Yttr Dependencies
	modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-api:5.0.2"
	[
		"core", "lockpick", "fractal", "tunnel", "phantom", "waypoint", "weld",
		"sandman", "crowbar", "keygen", "dessicant", "deferral", "machination", "util", "ripple",
		"recoil", "mesh", "aqi"
	].each { module ->
		modImplementation "com.unascribed:lib39-${module}:1.5.0-pre3+1.19.2"
	}
	modImplementation "curse.maven:fabric-disable-custom-worlds-advice-401978:3827588"

	// FractalJEI
	include(modImplementation("thelm.fractaljei:FractalJEI-Lib39:1.0.2"))

	// Yttr
	modImplementation "curse.maven:yttr-467267:6861187"
}

def replacements = [
	"0@VERSION@": version
]

blossom {
	replaceToken(replacements)
}

processResources {
	inputs.properties(replacements)
	filesMatching(["mcmod.info", "META-INF/mods.toml", "META-INF/neoforge.mods.toml", "fabric.mod.json"]) {
		filter {
			it.replace(replacements)
		}
	}
}

def manifestAttributes = [
	"Specification-Title": modName,
	"Specification-Vendor": vendor,
	"Specification-Version": specVersion,
	"Implementation-Title": archivesName,
	"Implementation-Version": version,
	"Implementation-Vendor": vendor
]

jar {
	manifest.attributes(manifestAttributes)
}

sourcesJar {
	manifest.attributes(manifestAttributes)
}

publishing {
	publications {
		register("mavenJava", MavenPublication) {
			artifactId = archivesName
			artifact remapJar
			artifact remapSourcesJar
		}
	}
	repositories {
		if(project.hasProperty("CrystaelixMavenUsername") && project.hasProperty("CrystaelixMavenPassword")) {
			maven {
				name = "CrystaelixMaven"
				url = "https://maven.crystaelix.com/releases/"
				credentials(PasswordCredentials)
			}
		}
	}
}

publishMods {
	file = remapJar.archiveFile
	version = displayName = project.version
	changelog = file("changelog.md").text
	type = STABLE
	modLoaders.add("fabric")
	additionalFiles.from(remapSourcesJar.archiveFile)

	curseforge {
		accessToken = providers.gradleProperty("curseforge.token")
		projectId = "1496726"
		minecraftVersions.add(mcVersion)
		requires "jei", "yttr"
		incompatible "emi"
	}

	modrinth {
		accessToken = providers.gradleProperty("modrinth.token")
		projectId = "YygSOzb7"
		minecraftVersions.add(mcVersion)
		requires "jei", "yttr"
		incompatible "emi"
	}
}
